### ISSUE TITLE
segfault on drag+drop

### ISSUE THREAD

**Issue by xaverdh** [mwh/dragon#8]
I get a segfault when trying to drag+drop an (utf-8 encoded) text file.

If hat matters, on startup I get the following warnings:
(dragon:26094): Gtk-WARNING **: 18:06:12.639: Could not find the icon 'text-plain'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(dragon:26094): Gtk-CRITICAL **: 18:06:12.639: gtk_icon_info_load_icon: assertion 'icon_info != NULL' failed

**Comment by xaverdh** [comment]
Right before the segfault, It says "Writing as URI: file:///home/[...]".

**Comment by markus1189** [comment]
Same here, but I do not even the the `Gtk-WARNING` :disappointed:

**Comment by markus1189** [comment]
Seems like it works with `gtk+3-3.24.5` but segfaults with `gtk+3-3.24.10` ...

In case that it helps, here is a backtrace:

```
(gdb) bt
#0  0x00007f8e226b74b1 in __strlen_avx2 () from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libc.so.6
#1  0x00007f8e22791268 in g_string_insert_len () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libglib-2.0.so.0
#2  0x00007f8e22fb09c3 in gtk_selection_data_set_uris () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#3  0x0000000000402d04 in drag_data_get ()
#4  0x00007f8e22de092a in _gtk_marshal_VOID__OBJECT_BOXED_UINT_UINTv () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#5  0x00007f8e22854f96 in _g_closure_invoke_va () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libgobject-2.0.so.0
#6  0x00007f8e22870b2d in g_signal_emit_valist () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libgobject-2.0.so.0
#7  0x00007f8e228715f4 in g_signal_emit_by_name () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libgobject-2.0.so.0
#8  0x00007f8e230a8e0d in gtk_drag_selection_get () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#9  0x00007f8e22dded2d in _gtk_marshal_VOID__BOXED_UINT_FLAGSv () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#10 0x00007f8e22854f96 in _g_closure_invoke_va () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libgobject-2.0.so.0
#11 0x00007f8e22870b2d in g_signal_emit_valist () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libgobject-2.0.so.0
#12 0x00007f8e228715f4 in g_signal_emit_by_name () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libgobject-2.0.so.0
#13 0x00007f8e22fafa2b in gtk_selection_invoke_handler () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#14 0x00007f8e22fb15a1 in _gtk_selection_request () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#15 0x00007f8e22dd9434 in _gtk_marshal_BOOLEAN__BOXEDv () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#16 0x00007f8e22854f96 in _g_closure_invoke_va () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libgobject-2.0.so.0
#17 0x00007f8e22870514 in g_signal_emit_valist () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libgobject-2.0.so.0
#18 0x00007f8e2287111f in g_signal_emit () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libgobject-2.0.so.0
#19 0x00007f8e23067724 in gtk_widget_event_internal () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#20 0x00007f8e22f29f36 in gtk_main_do_event () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#21 0x00007f8e22c888d5 in _gdk_event_emit () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgdk-3.so.0
#22 0x00007f8e22cd3c32 in gdk_event_source_dispatch () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgdk-3.so.0
#23 0x00007f8e2276e70e in g_main_context_dispatch () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libglib-2.0.so.0
#24 0x00007f8e2276e9a8 in g_main_context_iterate.isra () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libglib-2.0.so.0
#25 0x00007f8e2276eca2 in g_main_loop_run () from /nix/store/aldz750xb5k96mzxg4l29dsip28b376k-glib-2.60.7/lib/libglib-2.0.so.0
#26 0x00007f8e22f29095 in gtk_main () from /nix/store/8z0bwnjqhnjww3yxy5l70yrrdf6dbck0-gtk+3-3.24.10/lib/libgtk-3.so.0
#27 0x0000000000402a3e in main ()
```

**Comment by JohnAZoidberg** [comment]
Fixed with #16

**Comment by xaverdh** [comment]
I can confirm that the issue is indeed fixed when building from that commit.
Thanks!

**Comment by xaverdh** [comment]
Ah, would be nice to have a release containing this fix in the near future :-)

**Comment by markus1189** [comment]
Awesome, thanks for the fix!

**Comment by mwh** [comment]
@xaverdh All these seem stable so I have tagged v1.1.1 and there is a corresponding GitHub release. Thanks everybody for the reports and the fixes.

**Comment by markus1189** [comment]
@mwh you're welcome and thanks for this tool, I still remember how happy I was when I discovered it.  Still one of my favorite tool that "does one thing well" in my setup!
